hydra:
  run:
    dir: !ENV ${OUT}/${project.name}/${project.job}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: !ENV ${OUT}/${project.name}/${project.job}/${now:%Y-%m-%d}/${now:%H-%M-%S}

project:
  name: age
  job: ukb_kidney_volume
  seed: 42

trainer:
  gpus: 1
  max_epochs: 200
  benchmark: True
  deterministic: False  # not possible, since PyTorch did not implement maxpool deterministic backward path!
  #limit_train_batches: 0.1
  #limit_val_batches: 0.1
  #limit_val_batches: 0.25
  val_check_interval: 1.0
  #early_stop_callback: False
  resume:

model:
  norm: IN
  inputs: 4
  outputs: 2
  loss: 'l2'
  depth: 18
  use_layer: 3
  no_max_pool: False
  strides: [1,1,1,2]
  heteroscedastic: True
  position: False

optimizer:
  learning_rate: 1e-4
  weight_decay: 0.0

loader:
  batch_size: 8
  num_workers: 16

dataset:
  mode: volume
  data: !ENV ${DATA}/UKB/interim/ukb_kidney_preprocessed.h5
  group:
  info: !ENV ${DATA}/UKB/interim/ukb_all.csv
  column: age
  preload: True
  init_load: False
  fold: 0
  train: !ENV ${DATA}/UKB/interim/keys/train_imaging_kidney.dat  # containing keys with: key_left & key_right (left and right kidney)
  val:   !ENV ${DATA}/UKB/interim/keys/test_kidney.dat
  gradcam_val: !ENV ${DATA}/UKB/interim/keys/test_kidney_gradcam.dat
  debug:
  #debug: !ENV ${DATA}/UKB/interim/keys/debug_kidney.dat
  data_augmentation: True
  crop_size:
  crop_margins:
  #crop_size: [100, 125, 105]
  #crop_margins: [5, 5, 5]
  gamma_range: [0.7, 1.3]
  patch_size:
  mirror_axis: 1
