checkpoints:
  ukb_t1brain_volume:
    - age/1ayzb5cd
  ukb_t1brain_volume_meta:
    - age/
  ukb_fundus:
    - age/34ddronm
  ukb_fundus_meta:
    - age/
  ukb_heart_volume:
    - age/m26p8z02
  ukb_heart_volume_meta:
    - age/1rwscko7
  ukb_kidney_volume:
    - age/1bh3m89q
  ukb_kidney_volume_meta:
    - age/3her2bh1
  ukb_liver_volume:
    - age/18u6ol8i
  ukb_liver_volume_meta:
    - age/
  ukb_pancreas_volume:
    - age/3hcm7xhv
  ukb_pancreas_volume_meta:
    - age/
  ukb_spleen_volume:
    - age/l9ucgigm
  ukb_spleen_volume_meta:
    - age/
