checkpoints:
  ukb_t1brain_volume:
    - age/4c1lai26
  ukb_t1brain_volume_meta:
    - age/l0g2ezhr
  ukb_fundus:
    - age/bo6amjyz
  ukb_fundus_meta:
    - age/ozobb36b
  ukb_heart_volume:
    - age/1ercs77z
  ukb_heart_volume_meta:
    - age/n66wowpl
  ukb_kidney_volume:
    - age/s22hjd2i
  ukb_kidney_volume_meta:
    - age/pk08stjj
  ukb_liver_volume:
    - age/3tk7w5zk
  ukb_liver_volume_meta:
    - age/2kymrtzh
  ukb_pancreas_volume:
    - age/1lfxmnh7
  ukb_pancreas_volume_meta:
    - age/2gawfyoz
  ukb_spleen_volume:
    - age/1yyuu9tg
  ukb_spleen_volume_meta:
    - age/2onmap79

