wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1644591113
    t:
      1:
      - 1
      - 9
      4: 3.6.13
      5: 0.12.10
      8:
      - 5
