checkpoints:
  nako_t1brain_volume:
    - age/2dznv2jq
  nako_t1brain_volume_meta:
    - age/
  nako_fundus:
    - age/
  nako_fundus_meta:
    - age/
  nako_heart_volume:
    - age/12nwqha3
  nako_heart_volume_meta:
    - age/
  nako_kidney_volume:
    - age/2ycc28tt
  nako_kidney_volume_meta:
    - age/
  nako_liver_volume:
    - age/    # 39ntj8y3
  nako_liver_volume_meta:
    - age/
  nako_pancreas_volume:
    - age/2s6vs8t1
  nako_pancreas_volume_meta:
    - age/
  nako_spleen_volume:
    - age/342smv83
  nako_spleen_volume_meta:
    - age/
